[package]
name = "cvm-rs"
description = "Rust utility library for cvmts. Runs all the high performance code"
version = "0.1.1"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
neon = "1"
libc = "0.2.155"

# Required for JPEG
once_cell = "1.19.0"
turbojpeg-sys = "1.0.0"
rayon = "1.10.0"
